image: golang:latest

variables:
  REPO_NAME: gitlab.chainedfinance.com/chaincore/r2

stages:
  - test
  - build

before_script:
  - mkdir -p $GOPATH/src/$REPO_NAME
  - ln -svf $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

format:
    stage: test
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet -composites=false $(go list ./... | grep -v /vendor/)
      - go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile .testCoverage.txt

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/r2
    artifacts:
      paths:
        - r2