image: golang:1.10

variables:
  GO_PROJECT: gitlab.chainedfinance.com/chaincore/r2

stages:
  - build
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test