[[constraint]]
  name = "github.com/eddyzhou/log"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.7"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "gitlab.zhuronglink.com/chaincore/contract-gen"
  version = "0.0.5"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3"

[prune]
  go-tests = true
  unused-packages = true
